### ISSUE TITLE
Hourly Weather Entity Missing Information

### ISSUE THREAD

**Issue by sheckandar** [alexander0042/pirate-weather-ha#125]
Hi,

I noticed that the hourly weather entity is missing information such as wind speed and direction amongst other things:

### Hourly  Weather Entity:
```
forecast:
- datetime: '2023-07-09T17:00:00+00:00'
  precipitation_probability: 0
  condition: sunny
  humidity: 37
  cloud_cover: 0
  temperature: 25.4
  precipitation: 0

```

### Daily Weather Entity:
```
forecast: 
- datetime: '2023-07-09T06:00:00+00:00'
  precipitation_probability: 20
  wind_bearing: 146.67
  condition: rainy
  humidity: 33.7
  cloud_cover: 30
  temperature: 30.5
  templow: 15
  wind_speed: 13.39
  precipitation: 0.39
```

And below is a json response from an API call. It looks like there is a lot of information missing from both entities.

### Hourly API forecast:
```
{
  "time": 1688940000,
  "icon": "cloudy",
  "summary": "Cloudy",
  "precipIntensity": 0.0141,
  "precipProbability": 0.0,
  "precipIntensityError": 0.0155,
  "precipAccumulation": 0.0014,
  "precipType": "rain",
  "temperature": 21.66,
  "apparentTemperature": 23.16,
  "dewPoint": 10.48,
  "humidity": 0.43,
  "pressure": 890.1,
  "windSpeed": 20.21,
  "windGust": 30.6,
  "windBearing": 187.68,
  "cloudCover": 0.81,
  "uvIndex": 7.04,
  "visibility": 16.09,
  "ozone": 316.45
},
```
