### ISSUE TITLE
Home Assistant new Get weather forecast service

### ISSUE THREAD

**Issue by markmghali** [alexander0042/pirate-weather-ha#137]
Hello,

Thank you for all your work on this. Home Assistant has created a new service in the latest release 2023.9 called weather.get_forecast. Can please update the home assistant integration to reflect this change? 

Thank you Again 

![image](https://github.com/alexander0042/pirateweather/assets/17356528/7b939e49-6728-4a15-b146-f6f8b15cae76)

**Comment by dmbreakey** [comment]
You might be interested to know that [AstroWeather](https://github.com/mawinkler/astroweather) recently updated their integration to support the new service mode.

**Comment by langestefan** [comment]
> Since this is a HA specific issue, I'm also going to transfer this over to that repo, but I'll keep you updated there with progress!

FYI, this is still broken and will break the integration completely in a few months. 

> pirateweather::PirateWeather implements the `forecast` property or sets `self._attr_forecast` in a subclass of WeatherEntity, this is deprecated and will be unsupported from Home Assistant 2024.3. Please create a bug report at https://github.com/alexander0042/pirate-weather-ha/issues

**Comment by alexander0042** [comment]
Fixed in v1.3! It's listed a pre-release at the moment, but assuming there aren't any showstopping bugs I'll push it public next week!
Since there's already discussion of this in https://github.com/alexander0042/pirate-weather-ha/issues/136, I'm going to close this issue for now. Feel free to reply there about any problems though!

**Comment by markmghali** [comment]
upgraded to 1.3 and it fails to load now. 

![image](https://github.com/alexander0042/pirate-weather-ha/assets/17356528/5903753c-db2a-49ef-980a-1e805a985aaa)

**Comment by alexander0042** [comment]
Ok, well that's not good, but why I pushed this as a pre-release! Anything in the logs here?

**Comment by mermelmadness** [comment]
Mine is working, but I don't see the forecast entities.
![image](https://github.com/alexander0042/pirate-weather-ha/assets/38080873/51acad56-986a-4e78-a5e2-0994360f22ae)
![image](https://github.com/alexander0042/pirate-weather-ha/assets/38080873/90c57733-b4c1-4227-9b2b-30e09e20dee1)

**Comment by markmghali** [comment]
I thought you were looking for testing?  I am not seeing anything in the logs from what I can tell

**Comment by alexander0042** [comment]
@markmghali , very much looking for testing, so I appreciate this report! 
@mermelmadness , good to know your update worked. The only change to the user side of this if you see both the daily an hourly forecasts for the weather entity on the dashboard, There shouldn't be any changes to the sensors at all

**Comment by mermelmadness** [comment]
Well, yes, it works, but the old attribute sensors for forecast are gone.  This is expected with the new changes to weather integrations, but I thought that they would populate as individual sensors or entities with their own attributes.  I did add `0,1,2,3,4,5,6,7` to the configuration of the Sensors portion and I see them there with good data.  But missing are the forecast condition and temperatures, even though they are listed.

![image](https://github.com/alexander0042/pirate-weather-ha/assets/38080873/9df472bd-ac60-4240-b7b3-1a4eb47170fd)
![image](https://github.com/alexander0042/pirate-weather-ha/assets/38080873/5006a8d1-3cca-42cd-a09a-a8548d6ab1ef)
![image](https://github.com/alexander0042/pirate-weather-ha/assets/38080873/4a03acbf-9fe0-4c72-b24f-30f73ae24319)

**Comment by alexander0042** [comment]
Alas, they won't populate on their own unless sensors are selected. This is a bit of a controversial decision: https://community.home-assistant.io/t/petition-dont-delete-the-forecast-attribute/609298, but seems set in stone, so such is life. 

However, if you add those sensors in, they should show up! Can you try only using the temperature and condition sensors?

**Comment by alexander0042** [comment]
Note that for daily sensors, you need to use "Temperature High" and "Temperature Low". Maybe I should document this better in the config? i.e. having "daily monitored conditions" and "hourly monitored conditions"

**Comment by mermelmadness** [comment]
> Note that for daily sensors, you need to use "Temperature High" and "Temperature Low". Maybe I should document this better in the config? i.e. having "daily monitored conditions" and "hourly monitored conditions"

Ahh, yes, I selected those to be safe and they are now appearing, though it's annoying that I have to manually remove the sensors that I disabled (not your fault, just HA being HA).  I think this looks good, though now I have to go through a lot of automations and modify my MQTT scripts:

```
service: mqtt.publish
data:
  topic: wled/Weather/api
  payload: >-
    {"seg":[{"id":6,"n":"{{state_attr('weather.pirateweather','forecast')[1].temperature}}/{{state_attr('weather.pirateweather','forecast')[1].templow}}"}]}
```

**Comment by alexander0042** [comment]
Ideally I would base this off some other integration that creates sensors and allows them to be configured, but I couldn't find one that works. Also agree that this is going to be a big change, so not thrilled about the amount of work you'll have to go though. I don't know if there's a way around it though, and judging by the comments on that link I don't know if there is any other option other than sensors

**Comment by mermelmadness** [comment]
> Yea, I'd love to find a way to git rid of them automatically, but I couldn't figure it out!

No worries, and I figured out the MQTT command conversion relatively easily.

OLD:
```
service: mqtt.publish
data:
  topic: wled/Weather/api
  payload: >-
    {"seg":[{"id":6,"n":"{{state_attr('weather.pirateweather','forecast')[0].temperature}}/{{state_attr('weather.pirateweather','forecast')[0].templow}}"}]}
```

NEW:
```
service: mqtt.publish
data:
  topic: wled/Weather/api
  payload: >-
    {"seg":[{"id":5,"n":"{{states('sensor.pirateweather_daytime_high_temperature_0d') | round(0) }}/{{states('sensor.pirateweather_overnight_low_temperature_0d') | round(0) }}"}]}
```

**Comment by mermelmadness** [comment]
Ahh, one thing missing was in the old forecast attribute it gave the date of the forecasted day.  The new sensors lack that.  I'll have to figure out something else, then, to get the actual date of the forecasted day instead of just `2d` or `5d`

I used it in this script:

```
service: mqtt.publish
data:
  topic: wled/Misc/api
  payload: >-
    {"seg":[{"id":0,"n":"{{
    (state_attr('weather.pirateweather','forecast')[2].datetime)[:10] |
    regex_replace('^(\\d{4})-(\\d{2})-(\\d{2})$', '\\2/\\3')}}"}]}
```

**Comment by alexander0042** [comment]
Would it help to have a "time" sensor that provided the datetime for something? So there would be a "time_2d" sensor with a datetime value?

**Comment by alexander0042** [comment]
Great. They're easy enough to add in, so I'll push a 3.0.1 that adds them as an option

**Comment by mermelmadness** [comment]
Thank you.

A note to others making the change over.  The verbiage of the old `condition` attribute, which is now called `summary` or `daily_summary` has changed slightly.  `sunny` is now `Clear`, `rainy` is now `Rain`, `cloudy` is now `Cloudy`, and `partlycloudy` is now `Partly Cloudy`

**Comment by alexander0042** [comment]
I think icon should give you the previous values- the summary will one day be a text summary, while icon is meant for more machine readable stuff

**Comment by mermelmadness** [comment]
> I think icon should give you the previous values- the summary will one day be a text summary, while icon is meant for more machine readable stuff

Hmm, interesting.  The `icon` entities seems like it lines up with the MDI versions.  Will have to observe for a while to see which would work best.

**Comment by mermelmadness** [comment]
Sorry, side question.  Since this YAML configuration is now deprecated, where can we set the scan interval, or does it just default and hard code to 15 minutes?

```
  - platform: pirateweather
    api_key: NwO2w3mtm64kF6eLQrZL97TUeP641t8g7KoVv0Wt
    scan_interval: '00:02:15'
    monitored_conditions:
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed
```
