### ISSUE TITLE
Precipitation is null

### ISSUE THREAD

**Issue by jds11111** [alexander0042/pirate-weather-ha#24]
Many thanks for maintaining this integration. I am trying to compare different forecasters using the  `custom:apexchart-card`.
One of the plots is several different weather providers forecast for precipitation. I don't know what darksky did/does, but all of the other ones return the number zero for no precipitation, but pirateweather returns 'null'. Could this be changed to zero, also? Is this maybe something that needs to be addressed at pirateweather.net? Or, is it there to keep correspondence with darksky?

**Comment by alexander0042** [comment]
Hi,

Thanks for opening this- I love the idea of comparing the results of several forecasts, so this is a really cool implementation! I bet we can get this working, just need a couple of details. 

Biggest question here is if you're using this as a "sensor" or "weather" integration? Judging from your goal here, it sounds like the sensor would be the best choice. The detailed config for that is here: <https://www.home-assistant.io/integrations/darksky/>. If you use the "precip_accumulation", I think it'll show up as zero instead of null, but I'm not entirely sure. The null seems to come from the precipitation type, but since that's a text field, I don't know what else could be returned there? Precipitation intensity could also work here, but is a slightly different thing.

**Comment by jds11111** [comment]
Is it really either/or? I have added both parts to my configuration, so maybe I should use `sensor.pirateweather_precip_intensity_cm` ? Either way, there seems to be a consistency within HA for `weather.*` that isn't followed by pirateweather for the precipitation attribute.

BTW, I am comparing the following souces: Climacell, NWS, MET, AccuWeather and Pirateweather. The variation between these is itself interesting, and could be used to add uncertainties to predictions. Ideally after gathering data about predictions, and what actually comes to pass.

**Comment by alexander0042** [comment]
Not a limit at all- you can absolutely have them both at the same time (I do for my personal setup). Are you trying to compare the precipitation rate (or intensity, in mm/h), or accumulation (in mm)?

**Comment by jds11111** [comment]
I want to compare whatever is available in all of the integrations. That seems to be just precipitation, which is something like mm/hr. Some manipulation of the data seems to be required for getting accumulation. I used the statistics platform to create that from sensors.

**Comment by alexander0042** [comment]
Makes sense! You could probably add temperature or something similar?
If I'm understanding correctly, I'm thinking you probably want something like:

`sensor.pirateweather_precip_accumulation_0h`

for accumulated precipitation, stepping through either hours or days, depending on what the comparison is. Or:

`sensor.pirateweather_precip_intensity_0h`

for precipitation rate. So whichever one you're looking for should be there, no fancy processing required!

**Comment by jds11111** [comment]
But that just gives current or past precip, no? Not the forecast.

**Comment by alexander0042** [comment]
Sorry, wasn't super clear here. That gives the current conditions, but the forecast can be found that way too! The sensors are labeled sequentially, so either:
- `sensor.pirateweather_precip_accumulation_<x><p>`
- `sensor.pirateweather_precip_intensity_<x><p>`

where _x_ is the time step (1, 2, 3...) and _p_ is either `h` for hourly or `d` for daily! 

To expose these variables, my config looks like:
```
sensor:
    platform: pirateweather
    api_key: <apikey>
    scan_interval: '00:15:00'
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    hourly_forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
    monitored_conditions:
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed
      - precip_accumulation
```
  
which gives 12 hours of hourly forecasts and 7 days of daily forecasts
