### ISSUE TITLE
Pirateweather and Dark Sky Rich Weather card in HA

### ISSUE THREAD

**Issue by vanislman** [alexander0042/pirate-weather-ha#35]
Hi,
I installed your great API in Homassisstant through HACS. The API seems to work fine, and when I use the standard HA built-in weather card everything works.

I'm trying to use the Dark Sky Rich Weather card available through HACS, this is the GIT hub page:
https://github.com/clayauld/lovelace-darksky-card
The card definition section lists a bunch of mandatory sensors, which have to exist, like
```
entity_summary_today: sensor.pirateweather_summary_0d
entity_daily_summary: sensor.pirateweather_daily_summary
entity_forecast_high_temp_1: sensor.pirateweather_daytime_high_temperature_1d
entity_forecast_high_temp_2: sensor.pirateweather_daytime_high_temperature_2d
```
(I renamed dark_sky to pirateweather)
These sensors don't seem to exist. I also checked your python scripts, and can't find these.

Is your API not compatible with this Dark Sky card or am I missing something?

Thanks
Hermann

**Comment by alexander0042** [comment]
This is a really cool card, and a great test of my comparability! Let me try installing it to my instance and see what I can see

**Comment by alexander0042** [comment]
Well that's weird, it's working for me (and is a really nice card!), 

My configuration.yaml looks like:
```
sensor:
  - platform: pirateweather
    api_key: <API_Key>
    forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
    scan_interval:
      minutes: 5
      
```

and my lovelace config looks like:

```
type: 'custom:lovelace-darksky-card'
entity_current_conditions: sensor.pirateweather_icon
entity_temperature: sensor.pirateweather_temperature
entity_summary_today: sensor.pirateweather_summary_0d
entity_daily_summary: sensor.pirateweather_daily_summary
entity_forecast_high_temp_1: sensor.pirateweather_daytime_high_temperature_1d
entity_forecast_high_temp_2: sensor.pirateweather_daytime_high_temperature_2d
entity_forecast_high_temp_3: sensor.pirateweather_daytime_high_temperature_3d
entity_forecast_high_temp_4: sensor.pirateweather_daytime_high_temperature_4d
entity_forecast_high_temp_5: sensor.pirateweather_daytime_high_temperature_5d
entity_forecast_icon_1: sensor.pirateweather_icon_1d
entity_forecast_icon_2: sensor.pirateweather_icon_2d
entity_forecast_icon_3: sensor.pirateweather_icon_3d
entity_forecast_icon_4: sensor.pirateweather_icon_4d
entity_forecast_icon_5: sensor.pirateweather_icon_5d
entity_forecast_low_temp_1: sensor.pirateweather_overnight_low_temperature_0d
entity_forecast_low_temp_2: sensor.pirateweather_overnight_low_temperature_1d
entity_forecast_low_temp_3: sensor.pirateweather_overnight_low_temperature_2d
entity_forecast_low_temp_4: sensor.pirateweather_overnight_low_temperature_3d
entity_forecast_low_temp_5: sensor.pirateweather_overnight_low_temperature_4d
entity_summary_1: sensor.pirateweather_summary_1d
entity_summary_2: sensor.pirateweather_summary_2d
entity_summary_3: sensor.pirateweather_summary_3d
entity_summary_4: sensor.pirateweather_summary_4d
entity_summary_5: sensor.pirateweather_summary_5d
```

Does this look similar to your setup?
