### ISSUE TITLE
Struggling With Install

### ISSUE THREAD

**Issue by bravesfan171** [alexander0042/pirate-weather-ha#39]
I have followed the instructions for install to a T through HACS but am not seeing any new integration come up in my HA settings. Is there anything I am possibly missing? Would appreciate any help!

**Comment by alexander0042** [comment]
Hi- thanks for trying out this integration! 
Just to get some more details here, have you edited your configuration.yaml file? The integration can't be configured using the GUI (yet!), so needs to be done manually at this point

**Comment by bravesfan171** [comment]
> Hi- thanks for trying out this integration!
> Just to get some more details here, have you edited your configuration.yaml file? The integration can't be configured using the GUI (yet!), so needs to be done manually at this point

Yes, here is my configuration below:
```
weather:
  - platform: pirateweather
    api_key: KEY
    # Additional optional values:
    latitude: 12.345678
    longitude: 12.345678
    mode: "hourly"
    name: Weather
```
And under sensor.yaml:
```
  - platform: pirateweather
    api_key: KEY
    scan_interval: '00:15:00'
    monitored_conditions:
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed
```

Not sure if I’ve done something wrong there or not. I installed the integration through HACS, restarted, then added those to the configuration and restarted again.
