### ISSUE TITLE
Creating Daily and Hourly weather entities

### ISSUE THREAD

**Issue by SkilledAlpaca** [alexander0042/pirate-weather-ha#54]
I'm having some trouble getting a daily and hourly sensor setup and someone suggested that it may not be possible, but I thought I would check. Below is the Pirate Weather configuration that I have in my `configuration.yaml`. Is this misconfigured?
```yaml
weather:
  - platform: pirateweather
    api_key: !secret pirateweatherapi
    latitude: !secret homelatitude
    longitude: !secret homelongitude
    mode: "hourly"
    name: pirateweatherapihourly
weather:
  - platform: pirateweather
    api_key: !secret pirateweatherapi
    latitude: !secret homelatitude
    longitude: !secret homelongitude
    mode: "daily"
    name: pirateweatherapidaily
```

**Comment by SkilledAlpaca** [comment]
Got some help elsewhere. Fixed `configuration.yaml`

```yaml
weather:
  - platform: pirateweather
    api_key: !secret pirateweatherapi
    latitude: !secret homelatitude
    longitude: !secret homelongitude
    mode: "hourly"
    name: pirateweatherapihourly
  - platform: pirateweather
    api_key: !secret pirateweatherapi
    latitude: !secret homelatitude
    longitude: !secret homelongitude
    mode: "daily"
    name: pirateweatherapidaily
```
