### ISSUE TITLE
sunset_time & sunset_time sensors missing

### ISSUE THREAD

**Issue by JCHH2** [alexander0042/pirate-weather-ha#58]
Hi!

I have added the following to my config `monitored_conditions:` 
```
- sunset_time
- sunrise_time
```
However, these sensors do not appear.
Is there something special about them?

**Comment by jchhenderson** [comment]
Hi

...and thank you for providing it! 👍 

I am using the HACS version with HA container.

I also noticed some other sensors (that I just added) also don't show
```
- temperature_high
- temperature_low
```

**Comment by alexander0042** [comment]
Interesting- do you see anything in the logs about this? I'll be honest, no one has asked about the sunset time sensors yet, so it hasn't been on my radar?

**Comment by chicknlil** [comment]
I just came here to report the same thing. I'm using pirate weather in conjunction with [Platinum Weather Card](https://github.com/Makin-Things/platinum-weather-card) and there are definitely things I can't fill in.  At the moment I'm needing to use multiple weather providers to fill the gaps.

**Comment by alexander0042** [comment]
I'm really sorry for my slow reply here. We have a 3-month old baby, and she is definitely taking a lot of the attention at the moment! 

To follow both these questions up with another question, are you using this integration as a [sensor](https://www.home-assistant.io/integrations/darksky) or [weather entity](https://www.home-assistant.io/integrations/weather.darksky/)? If these are as sensors, then these parameters should be working, so that's a bigger problem. 

If you're up for some light troubleshooting, I'd appreciate it if you could try this using the [new version of this integration](https://github.com/alexander0042/pirate-weather-ha/issues/57)? This moves everything to the Home Assistant standard, which should solve this issue, and still includes both the weather and sensor entities.

**Comment by jchhenderson** [comment]
> We have a 3-month old baby, and she is definitely taking a lot of the attention at the moment!
congratulations!

I am (trying to) use all 4 as sensors and cannot see any of them.  Also, which is correct?
- temperature_min
- temperature_max
or
- temperature_high
- temperature_low
-

**Comment by alexander0042** [comment]
Thanks! You'll want to use:
```
- temperature_high
- temperature_low
```
as the other ones are officially depreciated. Do you mind pasting in the full block of your configuration.yaml (without the API key!), so I can take a look at how it's laid out?

**Comment by chicknlil** [comment]
Here's mine...

```
  - platform: pirateweather
    api_key: xxxxxx
    scan_interval: '00:15:00'
    monitored_conditions:
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed
      - summary
      - icon
      - apparent_temperature
      - wind_gust
      - wind_bearing
      - temperature_high
      - temperature_low
      - temperature_min
      - temperature_max
      - apparent_temperature_high
      - apparent_temperature_low
      - apparent_temperature_min
      - apparent_temperature_max
      - uv_index
      - sunrise_time
      - moon_phase
      - sunset_time
      - alerts
      - minutely_summary
      - precip_accumulation
      - dew_point
      - pressure
      - ozone
      - visibility
      - hourly_summary
```

**Comment by jchhenderson** [comment]
this is mine (it's in a package)
```
weather:
  - platform: pirateweather
    api_key: !secret pirate_weather_api
    # Additional optional values:
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    mode: "hourly" # (default) or "daily"
    #name: Pirate Weather

sensor: 
  - platform: pirateweather
    api_key: !secret pirate_weather_api
    scan_interval: '00:15:00'
    units: uk2
    monitored_conditions:
    # temp
      - temperature
      - apparent_temperature
      - dew_point
      - temperature_high    # The daytime high temperature.
      - temperature_low
      - pressure
      - humidity
    # rain
      - precip_probability
      - precip_type
      - precip_intensity
    # clouds
      - cloud_cover
      - uv_index
#       - nearest_storm_distance
    # wind
      - wind_speed
      - wind_gust
      - wind_bearing
    # summaries
      - minutely_summary
      - hourly_summary
      - daily_summary
#       - alerts # US only
    # sun
      - sunrise_time
      - sunset_time
```

**Comment by chicknlil** [comment]
I still don't have max or min showing as options, after following the steps in the other topic you linked.

**Comment by alexander0042** [comment]
Ok, thanks for posting those configs, they explain what's going on here! 

What's happening is both sunrise/sunset and temperature_high/temperature_low are daily forecast parameters, not current conditions. This means that they aren't in requested data from the server, so don't show up. The fix here is to add: 
```
    forecast:
      - 0
```
under your api_key line for the sensors, similar to how it's described from the HA integration(<https://www.home-assistant.io/integrations/darksky>).

One thing I'm curious about is if these used to show up for Dark Sky and then stopped working when you switched to Pirate Weather, or if this is a new integration. One of my goals is backwards compatibility, so if it used to work, then that's an issue!

**Comment by chicknlil** [comment]
I wasn't using Darksky previously (because I knew it was going away). I found Pirate Weather while looking for a better weather integration that would work with the Platinum Weather Card I mentioned previously.

I had to further tweak my config.yaml after adding that line of code (removing reference to min/max, based on the error logs) ... that enabled me to do the check and restart.

That said, on restart it's working perfectly.  Here's the end result with the platinum weather card (and a mini graph card in between):
![Overview-–-Home-Assistant (4)](https://user-images.githubusercontent.com/100124187/203820104-b93b1bfe-e4a2-45d8-81f8-7c6d065e5fa6.png)

**Comment by jchhenderson** [comment]
>One thing I'm curious about is if these used to show up for Dark Sky and then stopped working when you switched to Pirate Weather, or if this is a new integration. One of my goals is backwards compatibility, so if it used to work, then that's an issue!

I never used DarkSkye either!

**Comment by alexander0042** [comment]
Love that weather card- I'll have to add it in to my configuration! I've tagged this as a documentation issue to remind me to clarify the instructions here on which variables are available for current conditions, which are hourly, and which are daily, since it's a pretty key detail!

Thanks again for using (and especially supporting!) this service, and let me know if you run into any other issues 🌤️

**Comment by jchhenderson** [comment]
> I wasn't using Darksky previously (because I knew it was going away). I found Pirate Weather while looking for a better weather integration that would work with the Platinum Weather Card I mentioned previously.
> 
> I had to further tweak my config.yaml after adding that line of code (removing reference to min/max, based on the error logs) ... that enabled me to do the check and restart.
> 
> That said, on restart it's working perfectly. Here's the end result with the platinum weather card (and a mini graph card in between): ![Overview-–-Home-Assistant (4)](https://user-images.githubusercontent.com/100124187/203820104-b93b1bfe-e4a2-45d8-81f8-7c6d065e5fa6.png)

Can you share your yaml for that card layout?

**Comment by chicknlil** [comment]
Sure. There's also a button card that's invisible unless there's a weather alert at the top...

```
type: vertical-stack
cards:
  - card:
      color: red
      color_type: card
      entity: sensor.pirateweather_alert_text
      layout: icon_state
      show_name: false
      show_state: true
      size: 100%
      styles:
        card:
          - height: 60px
        grid:
          - grid-template-areas: '"i s" "n n" "l l"'
          - grid-template-columns: 20% 1fr
          - grid-template-rows: 1fr min-content min-content
        state:
          - text-transform: uppercase
          - font-weight: bold
          - justify-self: start
      tap_action:
        action: fire-dom-event
        browser_mod:
          service: browser_mod.popup
          data:
            title: Alert Detail
            content:
              type: markdown
              content: >-
                ## {% if is_state('sensor.pirateweather_alerts','1')
                %}{{state_attr('states.sensor.pirateweather_alerts',
                'title')}}{% else
                %}{{state_attr('states.sensor.pirateweather_alerts',
                'title_0')}}{% endif %}  

                ### {% if is_state('sensor.pirateweather_alerts','0') %}No
                Weather Alerts {% elif
                is_state('sensor.pirateweather_alerts','1') %} Expires at {{
                state_attr('states.sensor.pirateweather_alerts', 'expires') |
                int | timestamp_custom("%-I:%M %p on %A")}} {% else %} Expires
                at {{ state_attr('states.sensor.pirateweather_alerts',
                'expires_0') | int | timestamp_custom("%-I:%M %p on %A")}} {%
                endif %}{% if is_state('sensor.pirateweather_alerts','1') %} {{
                state_attr('states.sensor.pirateweather_alerts', 'description')
                }} {% else %} {{
                state_attr('states.sensor.pirateweather_alerts',
                'description_0') }} {% endif %}
      type: custom:button-card
    conditions:
      - entity: sensor.pirateweather_alerts
        state_not: '0'
    type: conditional
  - card_config_version: 8
    daily_forecast_days: 5
    daily_forecast_layout: horizontal
    entity_apparent_temp: sensor.pirateweather_apparent_temperature
    entity_extended: sensor.pirateweather_minutely_summary
    entity_forecast_icon: sensor.pirateweather_icon
    entity_forecast_max: sensor.pirateweather_daytime_high_temperature_0d
    entity_forecast_min: sensor.pirateweather_overnight_low_temperature_0d
    entity_humidity: sensor.pirateweather_humidity
    entity_pop: sensor.pirateweather_precip_probability
    entity_pos: sensor.pirateweather_precip_probability
    entity_pressure: sensor.pirateweather_pressure
    entity_summary: sensor.pirateweather_summary
    entity_sun: sun.sun
    entity_temperature: sensor.pirateweather_temperature
    entity_todays_fire_danger: sensor.pirateweather_alerts
    entity_todays_uv_forecast: sensor.pirateweather_uv_index
    entity_uv_alert_summary: sensor.pirateweather_uv_index
    entity_visibility: sensor.pirateweather_visibility
    entity_wind_bearing: sensor.pirateweather_wind_bearing
    entity_wind_gust: sensor.pirateweather_wind_gust
    entity_wind_speed: sensor.pirateweather_wind_speed
    extended_name_attr: friendly_name
    extended_use_attr: false
    option_locale: US
    option_show_overview_decimals: true
    option_show_overview_separator: true
    option_time_format: 12hour
    option_tooltips: true
    overview_layout: complete
    section_order:
      - overview
      - extended
      - slots
      - daily_forecast
    show_section_extended: false
    slot_l1: forecast_max
    slot_l2: forecast_min
    slot_l3: pop
    slot_l4: remove
    slot_l5: remove
    slot_l6: remove
    slot_l7: remove
    slot_l8: remove
    slot_r1: sun_next
    slot_r2: sun_following
    slot_r3: remove
    slot_r4: remove
    slot_r5: empty
    slot_r6: remove
    slot_r7: remove
    slot_r8: remove
    text_card_title: Today's Forecast
    type: custom:platinum-weather-card
  - type: custom:mini-graph-card
    name: Temperature
    entities:
      - sensor.pirateweather_temperature
    hours_to_show: 24
    points_per_hour: 0.25
    color_thresholds:
      - value: 0
        color: '#ff0000'
      - value: 32
        color: '#ffff00'
      - value: 65
        color: '#00ff00'
      - value: 100
        color: '#0000ff'
  - card_config_version: 8
    custom1_icon: mdi:thermometer
    custom1_units: °F Outside
    custom1_value: sensor.b51788b47_remote_temperature
    custom2_icon: mdi:thermometer
    custom2_units: °F Inside
    custom2_value: sensor.thermostat_temperature
    entity_humidity: sensor.b51788b47_remote_humidity
    entity_pressure: sensor.pirateweather_pressure
    entity_uv_alert_summary: sensor.pirateweather_uv_index
    entity_visibility: sensor.pirateweather_visibility
    entity_wind_bearing: sensor.pirateweather_wind_bearing
    entity_wind_gust: sensor.pirateweather_wind_gust
    entity_wind_speed: sensor.pirateweather_wind_speed
    option_today_rainfall_decimals: true
    option_today_temperature_decimals: true
    overview_layout: title only
    section_order:
      - overview
      - extended
      - slots
      - daily_forecast
    show_section_daily_forecast: false
    show_section_extended: false
    show_section_slots: true
    slot_l1: custom1
    slot_l2: humidity
    slot_l3: wind
    slot_l4: pressure
    slot_l5: remove
    slot_l6: remove
    slot_l7: remove
    slot_l8: remove
    slot_r1: custom2
    slot_r2: uv_summary
    slot_r3: visibility
    slot_r4: empty
    slot_r5: remove
    slot_r6: remove
    slot_r7: remove
    slot_r8: remove
    text_card_title: Current Weather
    type: custom:platinum-weather-card
  - type: custom:mushroom-chips-card
    chips:
      - type: entity
        entity: sensor.pirateweather_alerts
        content_info: name
        name: Rain Radar
        icon: mdi:radar
        icon_color: indigo
        tap_action:
          action: navigate
          navigation_path: /lovelace/rain-radar
      - type: entity
        entity: sensor.pirateweather_alerts
        name: House Temps
        content_info: name
        icon: mdi:home-thermometer
        icon_color: light-green
        tap_action:
          action: navigate
          navigation_path: /lovelace/house-temps
    alignment: center
```
