### ISSUE TITLE
Using 2 locations with PirateWeather... worked in DarkSky...

### ISSUE THREAD

**Issue by mattlward** [alexander0042/pirate-weather-ha#61]
I have the following config, I have installed PirateWeather via HACS and renamed the folder to darksky.  It appears that my local home location is indeed being used, but my secondary location is not populated.  This config worked in darksky, can I not look at 2 locations?

```
#### PirateWeather acting as DarkSky ####
  - platform: darksky
    api_key: xxxxxxx
# Additional optional values:
    mode: "daily"
    name: Homer
    scan_interval:
# At least one of these must be specified:
      days: 0
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
    
#### PirateWeather acting as DarkSky ####
  - platform: darksky
    api_key: xxxxxxxxxxx
    name: Greenup
    latitude: 39.2478159
    longitude: -88.1633719
    mode: daily
    scan_interval:
  # At least one of these must be specified:
      days: 0
      hours: 0
      minutes: 15
      seconds: 0
      milliseconds: 0 
```

![image](https://user-images.githubusercontent.com/8540074/199731236-0afe28ab-a352-41d1-85e8-9402c707cc2f.png)

Adding my sensor config...
```
- platform: darksky
  api_key: !secret pirateweather-api
  forecast:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
  monitored_conditions:
    - summary
    - icon
    - temperature
    - summary
    - precip_probability
    - apparent_temperature
    - wind_speed
    - wind_gust
    - wind_bearing
    - humidity
    - temperature_high
    - temperature_low
    - nearest_storm_distance
    - nearest_storm_bearing
    - minutely_summary
    - hourly_summary
    - daily_summary
  scan_interval:
    # At least one of these must be specified:
    days: 0
    hours: 0
    minutes: 15
    seconds: 00
    milliseconds: 0
```
