### ISSUE TITLE
After removing pirateweather references from config.yaml, 0d sensors not present

### ISSUE THREAD

**Issue by chicknlil** [alexander0042/pirate-weather-ha#62]
hey @alexander0042 ... I was looking at my logs and they said to remove the pirateweather references from my config.yaml as they were no longer needed - I did, but now I no longer have access to those 0d sensors.  Did I miss something, or did the logs mislead me?

```
This error originated from a custom integration.

Logger: custom_components.pirateweather.weather
Source: custom_components/pirateweather/weather.py:137
Integration: Pirate Weather (documentation, issues)
First occurred: 10:26:59 AM (1 occurrences)
Last logged: 10:26:59 AM

Configuration of Pirate Weather (weather entity) in YAML is deprecated Your existing configuration has been imported into the UI automatically and can be safely removed from your configuration.yaml file
```

_Originally posted by @chicknlil in https://github.com/alexander0042/pirate-weather-ha/issues/58#issuecomment-1328074700_

**Comment by chicknlil** [comment]
Just the 0d sensors (and all of them, at that!).

**Comment by alexander0042** [comment]
Interesting- that's unusual to say the least, but not what should be happening! I'm going to apologize for the three step debugging process here, but I suspect something's gone off the rails in the updating process, and this should fix it. 

1. Remove all the existing Pirate Weather integrations via the GUI. 
2. Put the config lines back in your configuration.yaml and restart. This re-imports everything back in using the current version.
3. Comment the config lines back out and restart. Fingers crossed everything should stick around after this.

**Comment by chicknlil** [comment]
So I've gotten as far as step 2 (so no active integration, but the config elements in the config.yaml and restarted 2x) ...and checked the tab that I mostly use this view on.  It appears that ALL instances of Pirate Weather are now gone, as none of my weather cards are working.

So I'm thinking commenting those lines out won't improve anything at this point.  What do you think my next steps should be?

**Comment by alexander0042** [comment]
So believe it or not, that's actually sort of good news (although the fact that it broke everything is obviously really bad!). Do you mind checking the logs to see if there's anything from the integration? Should either be something along the lines of reading from the yaml or about an existing weather coordinator?

**Comment by chicknlil** [comment]
I have restarted several more times since then (trying to see if I did anything wrong, as my town's Pirate Weather kept reappearing) ... I think I figured THAT out, but there's nothing at all relating to Pirate Weather in the logs

**Comment by chicknlil** [comment]
Okay, now all signs of Pirate Weather are gone (except in the configuration.yaml, where my old config [I had to grab it from a backup on the 24th, when we'd made the changes] is back in place.)  Should my next step here be to reinstall the integration and THEN comment things out?  Or comment things out and THEN reinstall the integration?

**Comment by alexander0042** [comment]
Hmm, that's weird. One longstanding issue with Home Assistant is that browsers will cache the UI, so sometimes thing will appear even after they've been removed, although a couple refreshes usually fixes that. 

Great that you have backups here! Next step should be:1
1. Reinstall the integration
2. Make sure everything appears as it should
3. Comment things out and they should stick around

If you're comfortable with some light code changes, it would help if you added `_LOGGER.wanring('PW_UNIQUE_ID_A')` to line 118 of config_flow.py and `_LOGGER.wanring('PW_UNIQUE_ID_B')` to line 120. This is where it checks to see if there's already an existing integration and stops the code if there is. For some reason it seems like your system thinks there's an existing one even though there isn't, so this would help to troubleshoot it

**Comment by chicknlil** [comment]
I tried reinstalling the integration - none of the 0d sensors returned. (ARGH!).

In addition, where there were previously two ...I guess for lack of knowledge or better phrasing, I'll call them sub-integrations ... one for the Pirate Weather with all the sensors, one with just my town that was JUST weather ... there is now JUST the one for Pirate Weather.

And I use Edge, and have been clearing the browsing date (including cache in both regular and IE mode) and that doesn't seem to be making a difference.  I will try a reload or six, see if that helps.

I have *3* Pirate Weather related folders in my custom config: pirate-weather-ha; pirateweather; and pirateweather.old (which despite seeming empty in file editor, refuses to delete because it claims it's not empty).

**Comment by alexander0042** [comment]
To clarify where we are, your configuration.yaml looks something like:

```
sensor: 
  - platform: pirateweather
    api_key: !secret pirate_weather_api
    scan_interval: '00:15:00'
    units: uk2
    forecast:
      - 0
    monitored_conditions:
    # temp
      - temperature
      - apparent_temperature
      - dew_point
      - temperature_high    # The daytime high temperature.
    #Others...
```

That forecast: 0 line is pretty key, since it's what's saying to use the 0d conditions

**Comment by chicknlil** [comment]
Yes, see below.

```
  - platform: pirateweather
    api_key: !secret pirate_weather_api
    forecast:
      - 0
    scan_interval: '00:15:00'
    monitored_conditions:
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed
      - summary
      - icon
      - apparent_temperature
      - wind_gust
      - wind_bearing
      - temperature_high
      - temperature_low
      - apparent_temperature_high
      - apparent_temperature_low
      - uv_index
      - sunrise_time
      - moon_phase
      - sunset_time
      - alerts
      - minutely_summary
      - precip_accumulation
      - dew_point
      - pressure
      - ozone
      - visibility
      - hourly_summary
```

**Comment by alexander0042** [comment]
Thanks for posting that- unfortunately it's working on my end, which makes it harder to debug. One idea is to add a name attribute along the lines of: `name: TestLocation`. This will force the integration to create a new entity and makes things easier to track, which might help here?

**Comment by chicknlil** [comment]
Alright, here's what I ended up doing...

I re-added the integration again, and configured it twice. The first time I told it to set up sensors and weather, 7 day, 47(I believe?)  hourly.  The second time, I told it to do the same, but put 0 in both of those options.  That provided me with many options, and it *appears* to be working.

Now I don't imagine this is the best way to accomplish things but...

**Comment by alexander0042** [comment]
Definitely not the best way, but interesting nevertheless. So you ended up using the GUI to configure it? I expect that 95% of people will use the web interface going forward, so it's good to know that it is working at least

**Comment by chicknlil** [comment]
I did, since it didn't seem to be acknowledging the configuration.yaml.

**Comment by chicknlil** [comment]
So, I'd have mentioned this in the other thread, but since that OP was a dick, I hope you won't mind me bringing it up here.

That whole weather vertical stack that I shared in the other thread? Ever since I pulled out the stuff from the configuration.yaml, the "alert" box has been visible, even though there were no alerts present, after I made the correction to how my weather is now listed (my town_weather vs pirate_weather). I just got a notification on my phone about a weather alert though, and that DID make a change in how the popup presents - as expected.  Unfortunately, it's not feeding any information about the alert.

![Overview-–-Home-Assistant (7)](https://user-images.githubusercontent.com/100124187/204647625-90de523a-4b9a-4911-946f-3276e3f560a2.png)

Am I correct in presuming that the "alert" data should provide information on the weather alert? Or should I be trying to utilize another service for this?

**Comment by alexander0042** [comment]
This one may or may not be an easy answer. The Alert function is only working in the US at the moment (rest of the world is on the to-do list though!), so if you're outside of the US, then it won't show. 
If you're within the US, then this should be working, so we can go from there!

**Comment by alexander0042** [comment]
Update: this was definitely a bug! I'm just working out how to fix it, but I'll have a new version out tomorrow morning

**Comment by chicknlil** [comment]
Ah, yes I'm in the US, so I'm glad I could help in making you aware of the bug!

**Comment by alexander0042** [comment]
New version is up (<https://github.com/alexander0042/pirate-weather-ha/commit/df0e180fba442cb742342020e79c817709945eb4>)! I now remember thinking several months ago "I'll fix that before I finishing moving this to the new system", and them promptly forgot.

**Comment by chicknlil** [comment]
Dumb question. How do I apply this fix? I'm on my phone at the moment, so I won't be doing it until I'm back at my laptop. On a helpful note, we've got a weather alert right now so I'll be able to give you instant feedback.

**Comment by alexander0042** [comment]
Great question! Since this is still manual until I merge this branch to the primary, it's done the same way you initially installed the new version. So just follow the steps here: <https://github.com/alexander0042/pirate-weather-ha/issues/57#issue-1413669696>.

You may need to delete and add the integrations back in if the ID has changed, but otherwise should be good to go.

**Comment by chicknlil** [comment]
Oh boy. That didn't go smoothly at all.

First thing I encountered was that I already had a pirate-weather-ha folder, so it refused to clone into there. I swapped out of terminal (after trying and failing to change the name there) and went to file editor, renaming the folder to pirate-weather-ha.old.  I was then able to clone the pirate-weather-ha folder. I then completed the tasks, and on restart, it told me that the integration didn't exit (or something to that effect, sorry, I didn't capture it, my mistake).  So I deleted the existing integration, restarted again, 

I was able to readd the integration, and it added sensors (so it says, with the exact same names) but...

![image](https://user-images.githubusercontent.com/100124187/204871064-55a2fef1-9835-4d0e-9758-c1a2a3771f1f.png)

So clearly I've messed this up somewhere.

**Comment by alexander0042** [comment]
Ok, so the fact that it let you add it in is good! Can you click on the "entities" button in the integration interface- I suspect it's renamed them, which is why they've dropped off your card

**Comment by chicknlil** [comment]
The appear to all be renamed the same - `sensor.south_windsor_weather_alerts` for example.  Going into those cards and selecting those sensors returns no data.  Possibly related aside: these entities have been unavilable for the last two hours (basically, since adding them) and have this error in the info: `This entity is no longer being provided by the pirateweather integration. If the entity is no longer in use, delete it in settings.`

Searching through the logs, I found this:

```
This error originated from a custom integration.

Logger: custom_components.pirateweather
Source: custom_components/pirateweather/__init__.py:148
Integration: Pirate Weather (documentation, issues)
First occurred: 12:44:56 PM (1 occurrences)
Last logged: 12:44:56 PM

An existing weather coordinator already exists for this location. Using that one instead
```

**Comment by alexander0042** [comment]
Hmm, it really does seem to be frustratingly fragile here. Can you delete all the Pirate Weather integrations and add them in again? You shouldn't need to restart in between, for some reason it seems to be using the old entities with the new code, which won't work (hence the error)

**Comment by alexander0042** [comment]
I know this level of fragility is super irritating. The good news is that I shouldn't need to make any more changes to the entity_id, which means that this should be much less of an issue from now on

**Comment by chicknlil** [comment]
The good news: removing and readding the integration fixed the display of the weather in the cards.

The not so good news (though I may have muffed this up when I had to re-name everything from pirate_weather to south_windsor_weather): the alert is still showing as it did in [this comment](https://github.com/alexander0042/pirate-weather-ha/issues/62#issuecomment-1331310402).

I'm going to go back to the original code from [Reddit](https://www.reddit.com/r/homeassistant/comments/ethdvh/severe_weather_alert_card_with_popup_detail/),  and see if I updated everything correctly. I'll circle back in a bit.

**Comment by alexander0042** [comment]
That's something (can you tell I'm a relentless optimist here). The name comes from whatever you put in the config box, so that should explain it. 
If you clock on the alert entity in the GUI, do you see anything under the attributes? That should say if it's reading it in correctly at least

**Comment by chicknlil** [comment]
![image](https://user-images.githubusercontent.com/100124187/204903694-f804ccd2-5c83-46a9-94d8-fc9b4b138767.png)

I copied the code from the reddit post, changed all instances of dark_sky to south_windsor_weather and pasted it back in - and there were no differences (ie, it didn't prompt me to save). I did go back to the sensor data format I'd be using previously, but that didn't make a difference either.

Perhaps I should be abandoning this and asking this question instead: how can I parse the information from the alert and put it in a displayable format (right now, displaying the entity would just show 1 alert, rather than what the alert is)?  Am I making sense?

This setup lives on wall-mounted tablets that are most likely to be utilized by guests.

**Comment by alexander0042** [comment]
Ok, so at least the data is there. The simplest option for your purpose would be with a straightforward entity card, something like:
```
type: entity
entity: sensor.pirateweatheralerts2_alerts
attribute: description
state_color: true
```
This will show something like this, which will have the description of the alert:
![image](https://user-images.githubusercontent.com/26213938/204906653-3f7eee31-a5a2-41ea-a74e-01b4a93138fd.png)

**Comment by chicknlil** [comment]
Hmm.  Not quite as much information as I would have hoped.  Alright.  Thank you kindly for your assistance.  It's greatly appreciated!!

**Comment by alexander0042** [comment]
Got it- I don't like giving up on something!

Here's the working card code, replacing `sensor.pirateweatheralerts2_alerts` with whatever your sensor is named. Also worth noting that for now, the title is all that's passed along from the API, but it's high on my list of things to improve next year

```
card:
  color: red
  color_type: card
  entity: sensor.dark_sky_alert_text
  layout: icon_state
  show_name: false
  show_state: true
  size: 100%
  styles:
    card:
      - height: 60px
    grid:
      - grid-template-areas: '"i s" "n n" "l l"'
      - grid-template-columns: 20% 1fr
      - grid-template-rows: 1fr min-content min-content
    state:
      - text-transform: uppercase
      - font-weight: bold
      - justify-self: start
  tap_action:
    action: fire-dom-event
    browser_mod:
      service: browser_mod.popup
      data:
        title: Alert Detail
        content:
          type: markdown
          content: >
            ##{% if is_state('sensor.pirateweatheralerts2_alerts','1') %} {{
            state_attr('sensor.pirateweatheralerts2_alerts','title') }} {% else
            %} {{ state_attr('sensor.pirateweatheralerts2_alerts','title_0') }}
            {% endif %}  

            ###{% if is_state('sensor.pirateweatheralerts2_alerts','0') %} No
            Weather Alerts {% elif
            is_state('sensor.pirateweatheralerts2_alerts','1') %} Expires at {{
            state_attr('sensor.pirateweatheralerts2_alerts','expires') }} {%
            else %} Expires at {{
            state_attr('sensor.pirateweatheralerts2_alerts','expires_0') }} {%
            endif %} {% if is_state('sensor.pirateweatheralerts2_alerts','1') %}
            {{ state_attr('sensor.pirateweatheralerts2_alerts','description') }}
            {% else %} {{
            state_attr('sensor.pirateweatheralerts2_alerts','description_0') }}
            {% endif %}
  type: custom:button-card
conditions:
  - entity: sensor.pirateweatheralerts2_alerts
    state_not: '0'
type: conditional
```
