### ISSUE TITLE
Sensor name doesn't act as expected and renaming creates orphans

### ISSUE THREAD

**Issue by joaldes** [alexander0042/pirate-weather-ha#63]
I am using the precip_probability monitored condition and my app is up-to-date.  

The name of the sensor that gets created ends up as a concatenated string of 'Name' and sensor type (I think) instead of using just the 'Name'.

I set the sensor name to Zebra in my sensors.yaml file:
```
- platform: pirateweather
  name: Zebra
  api_key: 6mwfdaJRNy39nrnNIUXwXhUV7FxSmbZ8HSW9m253
  scan_interval: "00:05:00"
  monitored_conditions:
    - precip_probability
```

You can see in this screenshot, the newest sensor with 'Zebra' in the name contains more than just Zebra.  Further, renaming the sensor in the config leads to some duplicate orphan sensors:
[List of random sensors](https://i.imgur.com/eX1IQZ7.png)

Not sure what other info will be useful or what troubleshooting I can do.  Thanks!
