### ISSUE TITLE
After updating: Platform error weather.pirateweather - Integration 'pirateweather' not found.

### ISSUE THREAD

**Issue by cslink23** [alexander0042/pirate-weather-ha#80]
When I check my HA configuration, I get:
Platform error weather.pirateweather - Integration 'pirateweather' not found.

Running Home Assistant on Windows (portable).  PirateWeather has been working for 2 years.
Updated it today and received an error that module pyowm wasn't found.
After reading some googled-notes, I downloaded all files from the github and copied them into my pirateweather folder in custom_components.
I've commented out and back in my pirateweather configuration.yaml section:
```
weather:
  - platform: pirateweather
    api_key: <key_here>
    # Additional optional values:
    latitude: 35.914150
    longitude: -84.101690
    mode: "daily"   
    name: Weather
```

Not sure what else to try to get this working again.
